# Generated by Django 2.2.12 on 2020-06-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('active', models.BooleanField(default=False, verbose_name='激活')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回复ID')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数量')),
                ('view_num', models.IntegerField(default=0, verbose_name='访问数量')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('big_class', models.CharField(choices=[('科普', '科普'), ('财经', '财经'), ('健康', '健康'), ('游戏', '游戏'), ('美食', '美食'), ('读书', '读书'), ('设计', '设计'), ('股市', '股市'), ('电影', '电影'), ('汽车', '汽车'), ('军事', '军事'), ('情感', '情感'), ('旅游', '旅游'), ('艺术', '艺术')], max_length=32, verbose_name='分类')),
                ('type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('audio', '音频')], max_length=5, verbose_name='类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '话题',
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('M', '男'), ('W', '女')], default='M', max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('job', models.CharField(blank=True, max_length=128, null=True, verbose_name='职业')),
                ('education', models.CharField(blank=True, choices=[('小学', '小学'), ('初中', '初中'), ('高中', '高中'), ('大专', '大专'), ('本科', '本科'), ('研究生', '研究生')], max_length=16, null=True, verbose_name='学历')),
                ('intro', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/%d', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '个人资料',
            },
        ),
        migrations.CreateModel(
            name='Exponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans', models.TextField(blank=True, null=True, verbose_name='粉丝ID')),
                ('fans_num', models.IntegerField(default=0, verbose_name='粉丝数量')),
                ('concern', models.TextField(blank=True, null=True, verbose_name='关注ID')),
                ('concern_num', models.IntegerField(default=0, verbose_name='关注数量')),
                ('collect', models.TextField(blank=True, null=True, verbose_name='收藏ID')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('publish', models.TextField(blank=True, null=True, verbose_name='发布ID')),
                ('publish_num', models.IntegerField(default=0, verbose_name='发布数量')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数量')),
                ('zan_num', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('view_num', models.IntegerField(default=0, verbose_name='访问数量')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '个人指数',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('rep_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('zan_num', models.IntegerField(default=0, verbose_name='点赞')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评论',
                'ordering': ['-rep_time'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='文本')),
                ('vote', models.IntegerField(default=0, verbose_name='票数')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic', verbose_name='话题')),
            ],
            options={
                'verbose_name_plural': '文本选项',
            },
        ),
        migrations.CreateModel(
            name='ChoiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topic/image/%Y/%m/%d', verbose_name='图片')),
                ('vote', models.IntegerField(default=0, verbose_name='票数')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic', verbose_name='话题')),
            ],
            options={
                'verbose_name_plural': '图片选项',
            },
        ),
        migrations.CreateModel(
            name='ChoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='topic/audio/%Y/%m/%d', verbose_name='音频')),
                ('vote', models.IntegerField(default=0, verbose_name='票数')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic', verbose_name='话题')),
            ],
            options={
                'verbose_name_plural': '音频选项',
            },
        ),
    ]
